apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: chairwise-input-service
  name: chairwise-input-service
spec:
  replicas: 2
  selector:
    matchLabels:
      run: chairwise-input-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: chairwise-input-service
    spec:
      containers:
        - image: cvise/chairwise-input-service:latest
          name: chairwise-input-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always