version: "3"
services:
  outputapi:
    build: .
    expose: 
      - 8083
    ports:
      - 8083:8083
    restart: always
    networks:
      - outputnetwork
      - chairwise-sorting-service_sortingnetwork
networks:
  outputnetwork:
    driver: bridge
  chairwise-sorting-service_sortingnetwork:
    external: true